# Generated by Django 5.1.3 on 2025-03-14 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='manager_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todoapp.bosscustomuser'),
        ),
    ]
