# Generated by Django 5.1.3 on 2025-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_employeemodel_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='manage_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
