# Generated by Django 5.1.3 on 2025-03-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_employeemodel_manage_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
