# Generated by Django 5.1.3 on 2025-03-16 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerToUserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_duration', models.DateField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('task_title', models.CharField(blank=True, default='', max_length=255)),
                ('task_discreption', models.TextField()),
                ('task_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=100)),
                ('employee_user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todoapp.employeemodel')),
                ('manager_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todoapp.bosscustomuser')),
            ],
        ),
    ]
