# Generated by Django 5.1.3 on 2025-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_managertousertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managertousertask',
            name='task_discreption',
            field=models.TextField(default='', null=True),
        ),
    ]
