# Generated by Django 5.1.4 on 2025-03-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_alter_customuser_boss_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='manage_code',
        ),
    ]
