# Generated by Django 5.1.4 on 2025-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_remove_employeemodel_manage_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='employee_id_card',
            field=models.CharField(choices=[('Pancard', 'Pancard'), ('Aadharcard', 'Aadharcard')], default='Pending', max_length=255),
        ),
    ]
