# Generated by Django 5.1.3 on 2025-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_alter_employeemodel_employee_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Found', max_length=15),
        ),
    ]
