# Generated by Django 5.1.3 on 2025-03-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_employeemodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='employee_id_card',
            field=models.CharField(choices=[('Pancard', 'Pancard'), ('Aadharcard', 'Aadharcard'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
    ]
