# Generated by Django 5.1.3 on 2025-03-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_alter_employeemodel_employee_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='card',
            field=models.CharField(blank=True, default='Add', max_length=255),
        ),
    ]
