# Generated by Django 5.1.4 on 2025-03-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_alter_employeemodel_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
