# Generated by Django 5.1.5 on 2025-03-21 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0013_customuser_manager_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='emp_user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='manager_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='manegr_employee', to='todoapp.bosscustomuser'),
        ),
    ]
