# Generated by Django 5.1.5 on 2025-03-21 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0014_employeemodel_emp_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_user',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
