# Generated by Django 5.1.3 on 2025-03-21 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0015_alter_employeemodel_emp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(choices=[('Home Work', 'Home Work'), ('Office Work', 'Office Work'), ('Other', 'Other')], max_length=255)),
                ('task_description', models.CharField(max_length=255)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.CharField(max_length=255)),
                ('give_task', models.CharField(max_length=255)),
                ('suggetion_description', models.TextField(blank=True, default='', null=True)),
                ('d_date', models.DateField()),
                ('a_date', models.DateField(auto_now_add=True)),
                ('a_time', models.TimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.usertask')),
            ],
        ),
    ]
